- src/lib.rs
- src/main_loop.rs
- src/models/state/wallet/rusty_wallet_database.rs
- flush DB explicitly as this seems to reduce the size used by the wallet DB, see #14 
- Add some log output on startup before and after a step of the startup that might take a long time
- Only attempt to resync mutator set membership proofs once the client is caught up, i.e. has the most canonical tip known to peers.
> Reduce wallet disk usage issue 14

- src/bin/dashboard_src/history_screen.rs
- src/bin/dashboard_src/overview_screen.rs
- src/bin/dashboard_src/peers_screen.rs
- src/main_loop.rs
- src/models/blockchain/transaction/mod.rs
- src/models/blockchain/transaction/utxo.rs
- src/models/blockchain/transaction/validity/tasm/compute_indices.rs
- src/models/state/archival_state.rs
- src/models/state/wallet/address/generation_address.rs
- src/models/state/wallet/wallet_state.rs
- src/util_types/mutator_set/ms_membership_proof.rs
- src/util_types/test_shared/mutator_set.rs
Addresses #45
* Fixes clippy warnings about unnecessary vec![] and Arc<RefCell<..>>
* Applies cargo fmt
With this patch applied, both these commands run cleanly:
```
$ cargo clippy --all-features --all-targets
$ cargo fmt --check
```
Notes:
* running cargo version `1.72.0 (103a7ff2e 2023-08-15)`
* Changed all occurences of Arc<RefCell<..>> to Arc<Mutex<..>>.  These were only in the Dashboard.
Testing:
* Verified that Dashboard runs and navigated all screens
* ran `cargo test` without error
> Fix clippy warnings pr

- Cargo.lock
- Cargo.toml
- install-bash-completions.sh
- src/bin/neptune-cli.rs
addresses #43
Add `completions` sub-command that prints out completion code for present shell. Eg in bash do:
neptune-cli completions > ~/.bash_neptune_cli
echo "source ~/.bash_neptune_cli" >> ~/.bashrc
Supports bash, elvish, fish, powershell, zsh
Adds dependency on crate [clap_complete](https://docs.rs/clap_complete/latest/clap_complete/).
Notes:
* The present implementation is intended to make neptune-cli more ergonomic during development.
* `clap_complete` also supports compile time generation of completion shell scripts using build.rs.  Useful when installing binary for end user.  That solution is a little more complex, perhaps in the future and/or we can discuss if its worth doing in this PR.
* The `clap` project is working on a completion overhaul that would enable dynamic shell …
> add shell tab completions feature to neptune-cli

- developer_docs/uml_diagrams.md
Hi, as an aid to learning the code/data layout I generated some UML diagrams for neptune-core and related crates.  
The diagrams can be viewed at [tinyurl.com/neptune-diagrams](https://tinyurl.com/neptune-diagrams).
I thought they might be useful for other developers onboarding, hence this PR.
------------
**Notes**
This PR add a 1 line markdown file with a link to the UML diagrams.
The diagrams are being auto-generated and pushed to github nightly in a repo of mine.
If there are any other related/relevant crates you think I should add, please let me know.
The present list is neptune-core, twenty-first, tasm-lib, tasm-lang, triton-vm.
If you should wish to have the diagrams under the Neptune-Crypto account, you could fork my neptune-diagrams repo and either grant me push access, or run …
> add a page with link to UML diagrams.

- Cargo.lock
- Cargo.toml
- src/bin/dashboard_src/dashboard_app.rs
- src/bin/dashboard_src/history_screen.rs
- src/bin/dashboard_src/overview_screen.rs
- src/bin/dashboard_src/peers_screen.rs
- src/bin/dashboard_src/receive_screen.rs
- src/bin/dashboard_src/send_screen.rs
Addresses #52
Cargo.toml:
* removes tui dep
* adds ratatui 0.20.0 dep
Also updates dashboard src files to use ratatui instead of tui.
Testing:
Ran neptune-dashboard and verified that all screen/tabs load and appear to look correct.
Notes:
* tui is [unmaintained](https://github.com/fdehau/tui-rs/issues/654).
* ratatui v0.20.0 appears to be drop-in replacement for tui 0.19.0.   It builds and runs without error.
* ratatui v.0.21.0 and above deprecate some things and do not compile cleanly for the dashboard, so minor work will be required should we wish to use a later version.  For now though I prefer to keep the PR small so its easier to review.
* I opted to change `tui` references in code rather than aliasing `ratatui` to `tui` in Cargo.toml.
> Change tui dep to ratatui

- Cargo.lock
- Cargo.toml
Addresses #29.
bumps chrono dep to 0.4.30 which removed a dep on buggy time crate
See https://github.com/chronotope/chrono/releases/tag/v0.4.30
Specifically:
> Because time 0.1 has been unmaintained for years, however, the security advisory mentioned above has not been addressed. While chrono maintainers were careful not to break backwards compatibility with the time::Duration type, there has been a long stream of issues from users inquiring about the time 0.1 dependency with the vulnerability. We investigated the potential breakage of removing the time 0.1 dependency in chrono#1095 using a crater-like experiment and determined that the potential for breaking (public) dependencies is very low. We reached out to those few crates that did still depend on compatibility with time 0.1.
>
> As …
> update chrono dep to fix cargo audit warning

- src/bin/dashboard_src/overview_screen.rs
- src/lib.rs
- src/models/blockchain/block/block_height.rs
- src/models/blockchain/transaction/amount.rs
- src/models/state/mod.rs
- src/models/state/wallet/wallet_state.rs
- src/rpc_server.rs
- src/util_types/mutator_set/ms_membership_proof.rs
- src/util_types/mutator_set/removal_record.rs
- src/util_types/mutator_set/shared.rs
Addresses #6.  (partial)
The major objective of this PR is adding the `get_confirmations` RPC.   A secondary objective is displaying the confirmations field in overview screen of the Dashboard.   Other changes are ancillary.
Server:
* `implement get_confirmations` RPC
* return confirmations field in `get_dashboard_overview_data` RPC
* add `wallet_state::get_latest_balance_height()`
* add `block_height` to tuple returned from `wallet_state::get_balance_history`
Dashboard:
* display confirmations in overview screens
* change confirmations field from `usize` to `u64`
Notes:
* The `get_confirmations()` RPC function has been simplified and made more efficient than the prototype [here](https://github.com/Neptune-Crypto/neptune-core/issues/6#issuecomment-1732668472).
* …
> add get_confirmations() RPC and add to dashboard

- src/bin/dashboard_src/dashboard_app.rs
- src/bin/dashboard_src/history_screen.rs
- src/models/blockchain/transaction/amount.rs
- src/util_types/mutator_set/ms_membership_proof.rs
- src/util_types/mutator_set/removal_record.rs
- src/util_types/mutator_set/shared.rs
It was annoying me that the wallet history in the Dashboard exceeded the screen length and I could not scroll down to see the older entries.
This fixes that.    Up/Down arrows now work to move a selected row and it scrolls to end of list and back.   The impl is surprisingly manual.... I was expecting something like a `set scrollable=true` property on the widget, but no such luck.   Anyway, I based it on a [ratatui example](https://github.com/ratatui-org/ratatui/blob/main/examples/table.rs).
I originally had it wrapping around as per the example, but it was kind of surprising behavior, so now I made it stop at first entry when scrolling up and last entry when down. 
I wanted to add PgUp/PgDn support, but I couldn't find a way to get the number of visible rows in the table given that …
> History table scroll pr

- src/mine_loop.rs
- src/models/blockchain/transaction/amount.rs
- src/util_types/mutator_set/ms_membership_proof.rs
- src/util_types/mutator_set/removal_record.rs
- src/util_types/mutator_set/shared.rs
Addresses #57
Now uses state.cli.network instead of hard-coded string for the two occurrences previously identified in #57.
New (tested) log output:
```
2023-10-10T03:44:50.540462149Z  INFO ThreadId(05) neptune_core::mine_loop: Miner thread received alpha block height 00000000000000005102
```
> fix hard-coded "regtest" in log output

- src/bin/dashboard_src/history_screen.rs
- src/rpc_server.rs
This is a draft PR as a starting point for discussion of the changes mentioned below.
There is no existing issue for this, just a small change I thought would be useful.
This builds on #56 (not yet merged) and adds a height field to data returned from get_history() rpc.  This field is then displayed in the dashboard history screen.   Example:
It can be argued that height is not necessary to the wallet end-user and thus need not be displayed in dashboard history, but I would counter that:
* a CLI wallet like the dashboard will be used by devs and power users
* the height is a useful display field for me and probably others.
The position of the height column could be changed if desired.   I'm open to suggestions.  Also it could be called "block", "block height", or "height".  I chose the …
> Height in history pr

- .cargo/config.toml
- Cargo.lock
- Cargo.toml
- README.md
- src/config_models/cli_args.rs
- src/main.rs
Adds `--tokio-console` boolean cli arg to neptune-core.
When this flag is present, logging is configured to emit tokio tracing information and send it to localhost:6669 for processing by tokio-console.
This requires building tokio with the `tokio_unstable` build flag. This is specified in the new `.cargo/config.toml`
see: https://github.com/tokio-rs/console
Here's a screenshot of the `resources` view:
> feat: support for tokio-console

- README.md
- make rustup non-interactive
- rename heading to "installing"
- indicate where root is necessary
> improve installation instructions

- Cargo.lock
- Cargo.toml
- src/bin/dashboard_src/history_screen.rs
- src/bin/dashboard_src/peers_screen.rs
- src/config_models/cli_args.rs
- src/connect_to_peers.rs
- src/database/leveldb.rs
- src/database/rusty.rs
- src/lib.rs
- src/main_loop.rs
- src/mine_loop.rs
- src/models/blockchain/block/mod.rs
- src/models/database.rs
- src/models/state/archival_state.rs
- src/models/state/blockchain_state.rs
- src/models/state/light_state.rs
- src/models/state/mempool.rs
- src/models/state/mod.rs
- src/models/state/networking_state.rs
- src/models/state/wallet/mod.rs
- src/models/state/wallet/rusty_wallet_database.rs
- src/models/state/wallet/wallet_state.rs
- src/peer_loop.rs
- src/rpc_server.rs
- src/tests/shared.rs
- src/util_types/mutator_set/archival_mutator_set.rs
- src/util_types/mutator_set/rusty_archival_mutator_set.rs
- src/util_types/sync/tokio/atomic_mutex.rs
- src/util_types/sync/tokio/atomic_rw.rs
- src/util_types/sync/tokio/mod.rs
First off, I apologize for the size of this PR.   I normally keep PRs as small/focused as I can.
I started a branch while working on twenty_first storage in order to test those changes in neptune.   As I iterated on storage that led to the AtomicRw lock in twenty-first, which led to tokio AtomicRw in neptune.  At first I was replacing and refactoring (encapsulating) the existing locks and I wanted to be able to log/trace their activity, so I added a facility for that.   As I dug deeper I found that we still couldn't really guarantee concurrent write serialization at the highest level ie across Blockchain, Mempool, Wallet state.  So I experimented with a lock around GlobalState, and it appears to work well and also simplify code in the other State types as well.  Most other changes were …
> feat: global state lock, async leveldb, etc.

- src/bin/dashboard_src/dashboard_app.rs
- src/bin/dashboard_src/history_screen.rs
- src/bin/dashboard_src/overview_screen.rs
- src/bin/dashboard_src/peers_screen.rs
- src/bin/dashboard_src/receive_screen.rs
- src/bin/dashboard_src/send_screen.rs
The dashboard was constantly using around 15% CPU on my system while doing basically nothing.  This drops usage to under 1% for all screens.
The high usage was caused by constantly re-drawing the screen in the main loop.
The implemented fix is to add a `RefreshScreen` event which is sent by sub-screens when data or key events occur that require a redraw.
In this way, redraws only occur when required.
----
I am not certain this is the best or most elegant way to fix it, but it seems to works well on my system.
Testing: I tested functionality in all screens and compared with a dashboard instance running the previous code, and they appear to function identically, including the send screen which has some tricky stuff grabbing user input and moving control focus.
> fix: reduce dashboard CPU usage via fewer draws

- README.md
- developer_docs/.gitmessage
- developer_docs/git_branches.md
For consideration:
Let's consider this a first draft/proposal, and iterate from there.   The goal is to reach a written policy every team member can agree with and be happy with.
------
Adds written policy/guidelines for branch usage and updates the README to provide instructions for building the latest release branch or the tip.
The branch guidelines are an attempt to balance/integrate/codify several things:
1. standard `github flow` branching and PRs that most github devs are familiar with.
2. simplicity for devs, ie no need to commit changes to multiple branches in normal flow and also for now we allow direct commits to master by team members without review.
3. CI to ensure development tip of all triton/neptune crates always builds and passes tests.
4. specifies release branches for …
> add git branch guidelines,  update build instructions in README

- Cargo.toml
- benches/archival_mmr.rs
- src/models/blockchain/block/mod.rs
- src/models/blockchain/transaction/validity/tasm/verify_aocl_membership.rs
- src/util_types/mutator_set/archival_mmr.rs
- src/util_types/mutator_set/archival_mutator_set.rs
- src/util_types/mutator_set/chunk_dictionary.rs
Some optimizations of the archival-MMR which is used extensively by the archival mutator set. 
The method `prove_membership_async` changes its interface to only return the authentication path (membership proof) and not also the peaks of the MMR. If the peaks are needed, they can be requested separately.
`append` is more than 2x faster, and more than 10x (30x in one measurement) faster for the `append_and_persist` benchmark. The other benchmarks show improvements of around 20-50 %.
`append` and `batch_mutate_leaf_and_update_mps` are the most relevant methods, as they are used by the archival mutator set which is what we're aiming to speed up in #127.
Previous code:
```
Timer precision: 20 ns
archival_mmr                         fastest       │ slowest       │ median        │ mean …
```
> 126 speedup ammr

- src/lib.rs
- src/macros.rs
- src/models/state/mod.rs
closes #128
Adds a macro `log_duration` that logs execution time of a standard function and also `log_duration_async` for async functions.
The latter macro is then used to log the duration of `GlobalState::store_block_internal()`
The macros will make it easy to add timings for anything we care about, just by wrapping any existing fn with the appropriate macro.
The log-level is Debug, which is presently hard-coded into the macros.  Rationale:   I don't think users need to see this info in normal operation and also I wanted the macros to be dead-simple to use for wrapping existing functions (so I didn't make a log-level param).
**Example log output**
```
2024-04-06T05:54:59.783708912Z DEBUG ThreadId(01) neptune_core::models::state: at src/models/state/mod.rs:1189
-- executed async …
```
> feat: log duration of adding new block

- Cargo.lock
- src/bin/dashboard_src/overview_screen.rs
- src/main_loop.rs
- src/mine_loop.rs
- src/models/blockchain/block/mod.rs
- src/models/blockchain/transaction/mod.rs
- src/models/blockchain/transaction/validity/tasm/hash_index_list.rs
- src/models/state/archival_state.rs
- src/models/state/mempool.rs
- src/models/state/wallet/wallet_state.rs
This is my first contribution to Neptune  that addresses Issue #26 
I didn't quite follow in the code why the default value of of the timestamp is July 1, 2024, or perhaps value this is explained by some issue syncing to the blockchain on my machine, I am open to feedback on this.
> Remove emojihash from Neptune Dashboard Overview

- src/main_loop.rs
- src/mine_loop.rs
- src/models/blockchain/transaction/mod.rs
- src/models/channel.rs
- src/models/state/mod.rs
Partially addresses #122.
This PR makes the following potentially CPU intensive operations execute on tokio's blocking threadpool, so they do not block the tokio executor:
* `create_transaction_from_data()` which calls the prover
* the inner mining loop (still single-threaded)
* calls to triton_vm::program::Program::run() in `Transaction`
I am making this a PR rather than just pushing the commits for two reasons:
1. bring greater team awareness to the need to run any lengthy CPU ops on tokio's threadpool (or separate OS thread) and examples/methodology for doing so.
2. solicit input/suggestions as to other potentially lengthy/blocking computations.  (please comment in #122)
3. `spawn_blocking()` expects a non-async fn, so I changed the (inner) mining loop so it doesn't make any async …
> make long-running CPU tasks run on tokio's blocking threadpool.

- src/util_types/mutator_set/archival_mmr.rs
This PR is a response to Issue #125 
I chose to keep the `get_peaks_and_heights_async` and place the new functionality inside it rather than in `get_peaks` because the async function is used 5 or 6 times within the test suite.  I ran the benchmarks before and after the change and obtained the following results:
Master:
My PR:
In multiple runs I noticed the same small but consistent improvement on my machine, its possible that in setups with different tradeoffs between disk I/O and CPU speed, the difference would be more pronounced. 
EDIT: 
I definitely see even more gains after removing the `get_peaks_and_heights_async` function completely
> Optimize get_peaks_and_heights for archival MMR.

- src/models/blockchain/transaction/validity/tasm.rs
- src/models/blockchain/transaction/validity/tasm/proof_collection.rs
- src/models/blockchain/transaction/validity/tasm/proof_collection/claims.rs
- src/models/blockchain/transaction/validity/tasm/proof_collection/claims/store_collect_lock_scripts_claim.rs
- src/models/blockchain/transaction/validity/tasm/proof_collection/claims/store_k2os_claim.rs
- src/models/blockchain/transaction/validity/tasm/proof_collection/claims/store_rri_claim.rs
- src/models/blockchain/transaction/validity/tasm/proof_collection/store_removal_records_integrity_claim.rs
- test_data/0d9d5d3a40da7c9e1c36b9c0390aa3fa8e4e51550543c953b45c0648d26e0a0d110cab9b3b6ca012.proof
- test_data/2802e3ddc01ac5c17e148d3250c37a18b8271038325d78bdf4addf80efefc7e78c4260b40d408b54.proof
- test_data/283ca70810e042f133e4bb9ddb0939f191317aedab4262845c4d9a61fbd31f4c551a09128a31f270.proof
- test_data/4e9be1c1df1229cfb81d7cd6d004266376baea7b02284aac6e5cf7c08c725b1f5ea59a4257c1a3fa.proof
- test_data/5364505764d30e5771d1f1c7165254e77fad715b0d7c08582ec6da22530fa5c19a6a6c76a3566dcd.proof
- test_data/65d6be47fd2734317c1f41e663d0ed0e55a727bdc17e5af98f92d8e4add990a7516667c5eadec99d.proof
- test_data/738ac43c7fbe92be4b174859ee5b72b83b30c8df7db3c4c2f07bcddd9bfe8fe5acde36ce2f6f2b06.proof
- test_data/84bf4432da12725fce90abb1a5650d6bfda15ef31c0ed3c1e0de506b8401d54845cbc41761a5fb18.proof
- test_data/895605d29e5a39e81f018c82d300c38044df5f9f75d7ad968187e4a45b3965893f6cca23c88d2a97.proof
- test_data/bb2a368284a23ff11374823587aa407847f339262ebb3f8f7b72ad21b6765fe498c2705714ed47c9.proof
- test_data/c309bed6b36c131c56445ba588df664c8bf94b4bcae98538a798403ea69c16acf7726227e7e145e6.proof
- test_data/c5d809759791d4a3300c6e53d3927f5212080f3c7d5dc8649c03a1eff7a1fb09afda34303dae9087.proof
- test_data/cd16c05e5d52eb7ff48a93aa4bc48b4f2c7751a040f5160c76a6f1086d298e335901033a85b16954.proof
- test_data/d4fc9034fc3839a854a296bbf2470da14614519349f58539d230acc6228ad21c3140e9113e3c7d8e.proof
- test_data/d88252bda0c127d9e61d13e99f12ff2a4304e8232da0c8dd3d9822afeb6cb70b78c07c37930804a4.proof
- test_data/e65aab7d1c033a4e82ad0fc5e64ff343a46d7c8962abaa92a1a29ab89cb9a0d5b209989a0c497a1e.proof
- test_data/eb186ef807d8ff6a5f272ee92b50b43728fab0f569a8954a916e5fdd130f5908ee7696b3872b0125.proof
- test_data/ee513b03a9c2104f9f2fdbd2a731f482979975bf7658b48b0113568bb8fdf43e60180ac61252adb2.proof
Here's the pattern I would go with. I think it can be generalized somewhat to handle more claims as well, but I'm not sure that's actually a good idea. Let me know what you think.
> feat: Add snippet for storing RRI-claim in dyn memory

- src/models/blockchain/transaction/mod.rs
- src/models/blockchain/transaction/primitive_witness.rs
- src/models/blockchain/transaction/validity/removal_records_integrity.rs
- src/models/blockchain/type_scripts/time_lock.rs
Assert that a coinbase transaction has no inputs. This, combined with a potential future softfork requiring each block to have at least one input in its transaction, forces the miner to prove at least one execution of a `Merge` which removes any incentive to mine empty blocks. Mining empty blocks could otherwise be beneficial since it allows the miner to complete the proofs faster and get to the guessing part as soon as possible, to the detriment of the network.
> RemovalRecordIntegrity: Disallow coinbase when tx has inputs

- src/database/storage/storage_schema/dbtvec.rs
- src/database/storage/storage_schema/dbtvec_private.rs
- src/database/storage/storage_schema/simple_rusty_storage.rs
- src/database/storage/storage_schema/traits.rs
- src/main_loop/proof_upgrader.rs
- src/models/state/archival_state.rs
- src/models/state/wallet/rusty_wallet_database.rs
- src/util_types/mutator_set/archival_mmr.rs
- src/util_types/mutator_set/chunk_dictionary.rs
- src/util_types/mutator_set/rusty_archival_mutator_set.rs
Fix a problem in get_mutator_set_update_to_tip where the wrong removal records were returned.
The function attempts to find a `MutatorSetUpdate` that transforms the mutator set from a state B to a later state A where B and A can be separated by an arbitrary number of blocks. The problem was the the removal records were collecting from all blocks between B and A. But the MutatorSetUpdate data structure needs the removal records valid for block B.
To fix this, we make ephemeral changes to the archival mutator set to assemble the required information. And then roll those ephemeral changes back once the information is gathered.
This closes #225.
A solution where a "snapshot" of the archival mutator set was returned -- an archival mutator set that could read from the databases but only write …
> ArchivalMutatorSet: Fix get_mutator_set_update_to_tip

- src/lib.rs
- src/main_loop.rs
- src/main_loop/proof_upgrader.rs
- src/mine_loop.rs
- src/models/blockchain/transaction/mod.rs
- src/models/channel.rs
- src/models/peer/transaction_notification.rs
- src/models/peer/transfer_transaction.rs
- src/models/proof_abstractions/tasm/consensus_program_prover_job.rs
- src/models/state/mempool.rs
- src/models/state/mining_status.rs
- src/models/state/mod.rs
- src/models/state/tx_proving_capability.rs
- src/models/state/wallet/mod.rs
- src/models/state/wallet/wallet_state.rs
- src/tests/shared.rs
When we receive a new block, we might have to generate a Triton VM proof for the `update` program which can take minutes. This task was previously done during `set_new_tip`, specifically  in `Mempool::update_with_block_and_predecessor`. With this commit, we instead return the update jobs that need to be run and then spawn a task in which this expensive computation is performed, after the write-lock on `GlobalState` has been released.
There's one warning left in there intentionally, as I wasn't quite sure how to handle the returned `Vec<MempoolEvent>`. Maybe you, apart from the general architecture, @dan-da, can also see if we're using `Vec<MempoolEvent>` correctly here?
> Improve mempool tx update handling

- src/bin/dashboard_src/peers_screen.rs
- src/bin/neptune-cli.rs
- src/config_models/cli_args.rs
- src/connect_to_peers.rs
- src/main_loop.rs
- src/models/peer.rs
- src/models/state/mod.rs
- src/models/state/networking_state.rs
- src/peer_loop.rs
- src/rpc_server.rs
- src/tests/shared.rs
This commit adds a `reward` function on `PeerLoopHandler` that improves peers' standings when they
- send valid blocks
- send a valid block proposal
- send a valid transaction.
Notifications should not be rewarded because the thing they inform the recipient of might not be valid.
This commit also refactors `PeerInfo` and `PeerStanding` to better encapsulate logic and data and present the outside world with a smaller, abstract interface.
> feat: Reward peers for good behavior

- src/mine_loop.rs
- src/models/blockchain/block/mod.rs
- src/models/state/archival_state.rs
- src/models/state/mempool.rs
- src/models/state/mod.rs
- src/models/state/wallet/mod.rs
- src/tests/shared.rs
Prior to this fix, a race condition could lead to two different blocks being used in the witness composition for a new block. This happened since one block was input to the function, and inside the function to construct the coinbase transaction, a block was read from global state. With this fix, the block used as input argument is always used.
This closes #266.
> fix(mine_loop): Avoid using different blocks in block composition

- src/config_models/cli_args.rs
- src/connect_to_peers.rs
- src/main_loop.rs
- src/models/channel.rs
- src/models/peer.rs
- src/models/state/mod.rs
- src/peer_loop.rs
- src/tests/shared.rs
We are observing that people would like to participate in the network but can't because the two nodes listed in the README.md refuse connections. They do this because their max number of peers has already been reached.
This PR adds functionality for running a node in "bootstrapper mode", wherein it will drop the longest-lived peer connection whenever the maximum is reached. This mode is activated through a CLI argument. Whenever an incoming connection is established, if this mode is set, and if the max number of peers has been reached, the peer loop will send a  `DisconnectFromLongestLivedPeer` message to the main loop. The main loop iterates over all peers, filters out the peers given as CLI arguments, selects the one with the earliest connection established date, and instructs that …
> Bootstrapper Mode

- Cargo.toml
- benches/consensus.rs
- src/mine_loop.rs
- src/models/blockchain/transaction/primitive_witness.rs
- src/models/blockchain/transaction/transaction_kernel.rs
- src/models/blockchain/transaction/utxo.rs
- src/models/blockchain/transaction/validity/collect_type_scripts.rs
- src/models/blockchain/transaction/validity/removal_records_integrity.rs
- src/models/blockchain/transaction/validity/single_proof.rs
- src/models/blockchain/transaction/validity/tasm/claims/generate_collect_type_scripts_claim.rs
- src/models/blockchain/type_scripts/native_currency.rs
- src/models/blockchain/type_scripts/neptune_coins.rs
- src/models/blockchain/type_scripts/time_lock.rs
- src/tests/shared.rs
- src/util_types/mutator_set/mmra_and_membership_proofs.rs
- src/util_types/mutator_set/msa_and_records.rs
- src/util_types/mutator_set/root_and_paths.rs
Closes #199.
This moves all 'impl Arbitrary' and related functions into module 'neptune_arbitrary', which is built
if either:
1) --features arbitrary-impl
2) --tests
3) --test &lt;x>
4) --benches
5) --bench &lt;x>
It is necessary to include for tests because some unit tests require this functionality.
This modularization cleanly separates code that is only needed for arbitrary/testing from that which is necessary for debug/release builds.
I verified that both of these give no warnings or errors:
```
$ cargo clippy --all-features
$ cargo +nightly clippy --all-features --all-targets
```
> refactor: add 'arbitrary-impl' feature-flag

- src/connect_to_peers.rs
Fixes an inclusion error on a bounds test, resulting in peers in poor standing successfully establishing a connection.
> fix: Do not connect to banned peers

- src/config_models/data_directory.rs
- src/lib.rs
- src/models/blockchain/block/block_selector.rs
- src/models/state/archival_state.rs
- src/models/state/mod.rs
- src/models/state/wallet/monitored_utxo.rs
- src/peer_loop.rs
- src/rpc_server.rs
- src/tests/shared.rs
- src/util_types/mutator_set/archival_mmr.rs
feat(archival_state): Add archival block MMR
Add a new field to the archival state, `archival_block_mmr` which is an archival MMR of all block digests in the canonical chain. This allows the client to instantly check if a block belongs to the canonical chain, and thus to faster prune abandoned monitored UTXOs, which is the motivation for this addition.I n the future, this data structure will allow archival nodes to prove the canonicity of a block relative to a tip such that light nodes (that only see the current tip) can verify that any received blocks belong to the canonical chain.
Uses this new field to faster determine whether a block belongs to the canonical chain or not.
> Add archival block mmr to state

- src/config_models/cli_args.rs
- src/mine_loop.rs
Fixes #282.
The issue was caused by interference between rayon parallelism in disparate tokio tasks. On the one hand, the guesser spawned the max number of rayon threads using `repeat`. On the other hand, the peer loop task spawned rayon threads in the course of `triton_vm::verify` using `par_iter`. But since the the rayon threadpool was already occupied and since tokio tasks do not know how to coordinate about rayon's thread pool, the second task ended up stalling.
This PR fixes the problem by managing the rayon parallelism for guessing in a segregated rayon threadpool. It has already been experimentally verified to solve the problem. The [documentation](https://docs.rs/rayon/latest/rayon/struct.ThreadPool.html) for `ThreadPool` explains why:
> If the current thread is part of a …
> fix(`mine_loop`): Segregate rayon threadpool for guessing

- src/mine_loop.rs
- src/models/blockchain/block/mod.rs
- src/models/blockchain/block/validity/block_program.rs
- src/models/state/archival_state.rs
- src/models/state/mod.rs
- src/models/state/wallet/mod.rs
- src/peer_loop.rs
- Wrap call to `triton_vm::verify` in `spawn_blocking`.
- Make function `async` and percolate `async` markers.
- Sandwich relevant call between debug messages.
All observations point to this change eliminating issue #282. However, we do not have a mechanical explanation as to what causes the apparent fix.
> fix: Spawn task for block proof verification (#288)

- src/mine_loop.rs
- src/models/blockchain/block/validity/block_primitive_witness.rs
This PR makes PoW guessing faster ~3x faster, and apparently resolves the issue of the flakyness of the `hash_rate_independent_of_tx_size` test (when the test is run in isolation, it's still flaky when run in parallel with other tests but that is to be expected).
Running in test mode (opt-level 0), my machine goes from a hash rate of ~2'400 prior to this PR to a hash rate of ~7'800.
The solution is two-fold:
- Implement algorithm for optimal block-kernel MAST hash calculation, without updating timestamp and difficulty with each guess
- Restart guesser every N (currently set to 20) seconds to update timestamp and difficulty calculation, cf #149.
Complication:
- Notice that the `guess_restart_timer` is *never* allowed to resolve if the guesser is not running, as its resolution stops the …
> Faster guessing

- scripts/linux/provoke-block-syncing-mode.sh
- scripts/linux/run-multiple-instances-advanced.sh
- scripts/linux/run-multiple-instances-from-genesis-log-locks.sh
- scripts/linux/run-multiple-instances-from-genesis.sh
- scripts/linux/run-multiple-instances.sh
- src/config_models/cli_args.rs
- src/connect_to_peers.rs
- src/main_loop.rs
- src/mine_loop.rs
- src/models/blockchain/block/block_height.rs
- src/models/blockchain/block/mod.rs
- src/models/blockchain/block/validity/block_program.rs
- src/models/blockchain/block/validity/block_proof_witness.rs
- src/models/blockchain/transaction/mod.rs
- src/models/blockchain/transaction/validity/proof_collection.rs
- src/models/blockchain/transaction/validity/single_proof.rs
- src/models/blockchain/type_scripts/native_currency.rs
- src/models/channel.rs
- src/models/peer.rs
- src/models/peer/transfer_block.rs
- src/models/proof_abstractions/mod.rs
- src/models/proof_abstractions/verifier.rs
- src/models/state/archival_state.rs
- src/models/state/mempool.rs
- src/models/state/mod.rs
- src/peer_loop.rs
- src/tests/shared.rs
- Stylistic changes.
- Use verify wrapper, which uses true claims cache to bypass call to `triton_vm::verify` for tests.
- Move logic from `peer_loop` to `GlobalState`.
- Add rng on `PeerLoopHandler` to derandomize randomness in challenge.
- Add (positive) test with mocked communication between Alice and Bob whereby Bob triggers Alice to go into sync mode.
> test: Add test for sync challenge phase

- .github/workflows/main.yml
Also:
- don't rely on unmaintained [actions-rs](https://github.com/actions-rs)
- adhere to maximum line length in `main.yml`
> ci: Reject if documentation builds with warnings

- Cargo.lock
- Cargo.toml
- src/models/blockchain.rs
Simplify identification of to-be-reviewed snippets.
This is a PR because it uses an unreleased version of `tasm-lib`.
> test: Annotate snippet names with sign-off status

- Cargo.lock
- Cargo.toml
- src/models/blockchain/transaction/validity/collect_type_scripts.rs
- src/models/blockchain/transaction/validity/kernel_to_outputs.rs
- src/models/blockchain/type_scripts/native_currency.rs
@Sword-Smith, this should be in a decent state now. Opening a PR because merging this will invalidate proofs.
> chore(deps): Upgrade dependency `tasm-lib`

- src/models/blockchain/block/block_header.rs
- src/models/database.rs
- src/models/peer.rs
- src/models/state/archival_state.rs
- src/models/state/mod.rs
- src/peer_loop.rs
Add a new field to BlockRecord for the block's PoW witness which allows for the calculation of the block hash without needing knowledge of the entire block.
> feat(archival_state): Add block's PoW witness to `BlockRecord`

- src/models/blockchain/block/validity.rs
- src/models/blockchain/block/validity/block_program.rs
- src/models/blockchain/block/validity/coinbase_is_valid.rs
- src/models/blockchain/block/validity/correct_control_parameter_update.rs
- src/models/blockchain/block/validity/correct_mmr_update.rs
- src/models/blockchain/block/validity/correct_mutator_set_update.rs
- src/models/blockchain/block/validity/mmr_membership.rs
- src/models/blockchain/block/validity/predecessor_is_valid.rs
- src/models/blockchain/transaction/validity/collect_lock_scripts.rs
- src/models/blockchain/transaction/validity/collect_type_scripts.rs
- src/models/blockchain/transaction/validity/kernel_to_outputs.rs
- src/models/blockchain/transaction/validity/proof_collection.rs
- src/models/blockchain/transaction/validity/removal_records_integrity.rs
- src/models/blockchain/transaction/validity/single_proof.rs
- src/models/blockchain/transaction/validity/tasm/single_proof/merge_branch.rs
- src/models/blockchain/transaction/validity/tasm/single_proof/update_branch.rs
- src/models/blockchain/type_scripts/native_currency.rs
- src/models/blockchain/type_scripts/time_lock.rs
- src/models/proof_abstractions/tasm/environment.rs
- src/models/proof_abstractions/tasm/program.rs
The fallout from marking trait `ConsensusProgram` as `pub(crate)` suggests to me that the trait functions `source` and `run_rust` don't really belong in trait `ConsensusProgram`. Perhaps a `#[cfg(test)] trait ShadowedConsensusProgram` or similar could work.
> Make trait `ConsensusProgram` private

- src/bin/dashboard_src/send_screen.rs
- src/bin/neptune-cli.rs
- src/config_models/cli_args.rs
- src/main_loop/proof_upgrader.rs
- src/mine_loop.rs
- src/models/blockchain/block/mod.rs
- src/models/blockchain/block/validity/block_primitive_witness.rs
- src/models/blockchain/transaction/mod.rs
- src/models/blockchain/transaction/primitive_witness.rs
- src/models/blockchain/transaction/validity/tasm/single_proof/merge_branch/authenticate_coinbase_fields.rs
- src/models/blockchain/type_scripts/native_currency_amount.rs
- src/rpc_server.rs
- src/tests/shared.rs
Most importantly, add methods `display_n_decimals` and `display_lossless`.
Also:
- Refactor to avoid `BigInt` in conversions when possible. Percolate simpler types.
- Disambiguate `from_str` by renaming to `coins_from_str`.
> Lossless Display for `NativeCurrencyAmount`

- src/models/proof_abstractions/tasm/prover_job.rs
The padded height is shown before a proving job starts, but it's only the padded height from the processor table (which often but not always dominates). With this PR, the actual proof complexity (dominating padded height) is printed once the job is done, as the proof (if well-formed) will contain this data.
Logging the proving speed would also make a lot of sense, dividing the (real) padded height with the time it took to produce the proof. That's not included in this PR, as I couldn't find a place in the code in the pipeline where both the time and the proof were in scope.
> trace(ProverJob): More info about job complexity

- README.md
- docs/src/neptune-core/overview.md
- src/bin/neptune-cli.rs
- src/bin/neptune-dashboard.rs
closes #376.   (see for rationale)
modifies neptune-cli and neptune-dashboard to both use the same argument for specifying neptune-core rpc port:
```
-p, --port <port>          Sets the neptune-core rpc server localhost port to connect to [default: 9799]
```
also updates README and mdbook docs.
> chore: normalize --port arg between rpc clients

- src/lib.rs
When running the client, I want WARN log messages to catch my attention. But these warnings from the duration-checker completely spam my log output so I don't notice other warnings.
With this change, the messages are still printed but only with the DEBUG severity.
> trace: Reduce severity of duration-check log message

- .github/workflows/main.yml
- src/models/proof_abstractions/tasm/program.rs
Make trait `ConsensusProgram` public again, fixing the build failure of the benchmark.
Also make sure that continuous integration picks up on blunders like these in the future by building all benchmarks.
fix #365, fix #377
> fix: Fix benchmark build

- src/main_loop/proof_upgrader.rs
- src/mine_loop.rs
- src/models/blockchain/block/mod.rs
- src/models/blockchain/block/validity/block_program.rs
- src/models/blockchain/transaction/primitive_witness.rs
- src/models/state/archival_state.rs
- src/models/state/mempool.rs
- src/models/state/mod.rs
- src/models/state/wallet/mod.rs
- src/models/state/wallet/rusty_wallet_database.rs
- src/models/state/wallet/sent_transaction.rs
- src/models/state/wallet/transaction_output.rs
- src/models/state/wallet/unlocked_utxo.rs
- src/models/state/wallet/wallet_state.rs
- src/peer_loop.rs
- src/rpc_server.rs
- src/tests/shared.rs
addresses #364.   (lays groundwork)
This PR records details of sent tx in the wallet-db.
This ensures that wallets will have sufficient metadata to group together utxos related to a single payment, eg when displaying wallet history.
It is also used for adding a 2 payments per block rate limit implemented in the rpc send APIs.  This limit applies only until block height 25000, approx 5.6 months after launch.
Changes:
* add SentTransction type in sent_transaction.rs
* add RustyWalletDatabase::sent_transactions: DbtVec<SentTransaction>
* some fn now take references instead of owned values, to avoid clone.
* create_transaction_with_prover_capability() returns TransactionDetails
* impl serialize traits for TxOutput, TxOutputList, UnlockedUtxo
* make UnlockedUtxo pub
* add …
> feat: record sent tx details in wallet, rate-limit sent payments to 2 per block.

- src/main_loop.rs
A miner who finds a new block wants it to be broadcast to peers immediately so they have best chance to win the lottery race.
Previously a mined block was not being broadcast until after set_new_self_mined_tip() which is an expensive function.
The benefit to doing it that way is we can be certain we will have the block when a peer rqquests it.
This commit broadcasts the new block announcement before calling set_new_self_mined_tip().
However it does it inside a global state write-lock, ie:
1. obtain write-lock
2. broadcast to peers
3. set_new_self_mined_tip()
4. release write-lock.
As such, any incoming peer request will have to acquire a read-lock which cannot happen until set_new_self_mined_tip() completes.
-----
it has worked fine thus far in limited testing.   ie, I was able to mine …
> perf: announce mined block to peers immediately.

- src/models/blockchain/transaction/mod.rs
- src/models/blockchain/transaction/transaction_kernel.rs
- src/peer_loop.rs
- src/util_types/mutator_set/removal_record.rs
Funnel all tests related to unconfirmability to one function, with optional error code. Improve log messaging when receiving unconfirmable transactions from peers.
> refactor: Factor out unconfirmability

- src/mine_loop.rs
note the "guessing for 240 seconds".   It doesn't loop back to 0 every 20 seconds anymore.
fixes #405
Refactors mining loop a bit such that:
1. state transition from not-guessing to guessing is identifiable.
2. state transition from guessing to inactive is identifiable.
3. globalState mining_status is set to guessing when guessing starts
4. mining_status is set to inactive when guessing ends.
Previously mining_status was being set to guessing when guessing first starts, then inactive after 20 seconds, then guessing again, then inactive after 20 seconds, and so on until a block is found or guessing is cancelled.  Thus the max reported duration of guessing was 20 seconds.
With this change, the reported duration accurately reflects the actual amount of time spent in the guessing state, …
> fix: report guessing time correctly

- src/main_loop.rs
- src/mine_loop.rs
- src/models/blockchain/block/mod.rs
- src/models/blockchain/transaction/utxo.rs
- src/models/channel.rs
- src/models/state/block_proposal.rs
- src/models/state/mod.rs
- src/models/state/wallet/address/hash_lock_key.rs
- src/models/state/wallet/incoming_utxo.rs
- src/models/state/wallet/mod.rs
- src/models/state/wallet/wallet_state.rs
- src/models/state/wallet/wallet_status.rs
- src/rpc_server.rs
- src/tests/shared.rs
The guesser UTXOs are locked through a `RawHashLock`. Only the guesser is knowledgeable of the key that can release this lock.
Prior to this PR, this key was already deterministically derived from the wallet secret and the previous block hash. Despite this deterministic derivation, the rest of the pipeline assumed no such structure. In particular, a successful guesser task would pass the guesser preimage upstream; and explicit `ExpectedUtxo`s would be generated so that the wallet can claim these UTXOs.
This commit
- Modifies the wallet update function so that it checks an incoming block against what the guesser preimage would be if this wallet had been the one to guess it. This change obviates the need to transmit `ExpectedUtxo`s to the wallet update function.
- Removes the parts of the …
> Automatic Recognition of Guesser UTXOs

- src/config_models/cli_args.rs
- src/connect_to_peers.rs
- src/main_loop.rs
- src/models/peer/peer_info.rs
- src/peer_loop.rs
- src/rpc_server.rs
Previously, if a node had more active connections than specified in `max_num_peers`, it disconnected from a single one each time peer discovery ran.
Now, as many connections as required are terminated.
> fix: Potentially disconnect from multiple peers

- src/config_models/cli_args.rs
- src/connect_to_peers.rs
- src/main_loop.rs
- src/peer_loop.rs
- src/rpc_server.rs
Remove various casts from `u16` to `usize`.
The command line argument `max_num_peers` is almost always used as a `usize`. The only exception is a single test.
> Make `max_num_peers` a `usize`

- src/config_models/cli_args.rs
- src/connect_to_peers.rs
- src/main_loop.rs
- src/models/state/networking_state.rs
- src/peer_loop.rs
In order to reduce the potential connection flood, rapid re-connection attempts after a disconnect are ignored.
If node A decides to (gracefully) terminate the connection to some node B, then node A blocks any connection attempts from node B for some time. The cool-down time can be configured through the command-line interface's argument “reconnect_cooldown”. The argument is given in seconds. The default is 30 seconds.
~~This introduces a breaking change because the public enum `ConnectionRefusedReason` gets a new variant `RecentlyDisconnected`. This enum is now marked `#[non_exhaustive]` to prevent future variant additions from being breaking again.~~
This introduces a breaking change because the public structure `NetworkingState` gains a new, private field.
> Refuse connections from recent disconnects

- src/main_loop.rs
- src/tests/shared.rs
Reconnecting to peers specified on the command line does not share any logic with discovering new peers. Separate the two functions to increase readability, maintainability, and testability.
Also:
- release read locks on global state sooner
- increase accuracy of comments describing peer discovery
- simplify tests
- adhere to the maximum line length (100)
- adhere to the maximum comment length (80)
The now-standalone method `reconnect` is not tested yet. This is almost identical to previous testing behavior, where the “reconnect” logic was only incidentally invoked when testing the “peer discovery” logic. I consider testing `reconnect` out of scope for this PR. If the PR gets accepted, a corresponding issue can be opened.
> Separate reconnecter from peer discovery

- .github/workflows/main.yml
- src/bin/neptune-cli.rs
- src/config_models/cli_args.rs
- src/config_models/data_directory.rs
- src/lib.rs
- src/main_loop.rs
- src/main_loop/proof_upgrader.rs
- src/mine_loop.rs
- src/models/blockchain/block/block_height.rs
- src/models/blockchain/block/mod.rs
- src/models/blockchain/block/validity/block_program.rs
- src/models/state/archival_state.rs
- src/models/state/mempool.rs
- src/models/state/mod.rs
- src/models/state/wallet/address/address_type.rs
- src/models/state/wallet/mod.rs
- src/models/state/wallet/scan_mode_configuration.rs
- src/models/state/wallet/secret_key_material.rs
- src/models/state/wallet/transaction_output.rs
- src/models/state/wallet/wallet_configuration.rs
- src/models/state/wallet/wallet_entropy.rs
- src/models/state/wallet/wallet_file.rs
- src/models/state/wallet/wallet_state.rs
- src/peer_loop.rs
- src/rpc_server.rs
- src/tests/shared.rs
Scan Mode is a possible configuration on the `WalletState` which activates a new step in the main wallet state updater function: if the block is in range, it is also scanned for encrypted public announcements decryptable by *future* spending keys. The situation occurs frequently in practice when users import their wallet seed onto a new machine -- losing all wallet information but the seed. By configuring (through CLI arguments) the range of blocks and the number of future keys to scan with, such users can recover UTXOs bound for them provided that there is an on-chain announcement. Scan mode is also activated (with default parameters) when, at boot, the client finds a `wallet.dat` file but no matching wallet database directory -- a strong indicator that the wallet seed was imported. …
> feat: Scan Mode

- src/main_loop/proof_upgrader.rs
- src/models/blockchain/block/mod.rs
- src/models/blockchain/block/mutator_set_update.rs
- src/models/blockchain/transaction/lock_script.rs
- src/models/blockchain/transaction/mod.rs
- src/models/blockchain/transaction/primitive_witness.rs
- src/models/blockchain/transaction/transaction_kernel.rs
- src/models/blockchain/type_scripts/mod.rs
- src/models/blockchain/type_scripts/time_lock.rs
- src/tests/shared.rs
- src/util_types/mutator_set.rs
- src/util_types/mutator_set/authenticated_item.rs
Close #481 by way of (1): "Transaction initiator retains the original PritmitiveWitness, upgrades it to the new block, and then attempts to make a new ProofCollection that can then be shared."
Fixes broken `PrimitiveWitness::validate`.
> Thv/ 481 pw to pc upgrade race condition

- src/models/blockchain/block/mod.rs
- src/models/state/mod.rs
- src/models/state/tx_creation_artifacts.rs
- src/models/state/tx_creation_config.rs
Drop the field `selection` from `TxCreationArtifacts` as the task of keeping track of unconfirmed spent UTXOs can be handled by the mempool
> refactor: Use mempool to avoid double-spends

- src/config_models/cli_args.rs
- src/connect_to_peers.rs
- src/main_loop.rs
- src/models/channel.rs
- src/models/peer.rs
- src/models/peer/bootstrap_info.rs
- src/models/state/networking_state.rs
- src/peer_loop.rs
In order to help newcomers to connect to peers on the network, certain nodes act as bootstrap nodes. Those nodes tend to be well known, and users tend to specify them as potential peers via command line arguments.
Previously, connections to potential peers specified as command line arguments were always re-initiated when dropped. This can cause an involuntary denial-of-service of those well-known bootstrap nodes.
With this PR, a well-connected node does not initiate connections with bootstrap nodes.
> Leave bootstrap nodes alone if well connected

- src/models/blockchain/block/block_height.rs
- src/models/blockchain/block/block_validation_error.rs
- src/models/blockchain/block/mod.rs
We discovered that the number of inputs allowed into a block had a much lower practical limit than we intended. The problem is that the `inputs` field of the `TransactionKernel` holds up to 45 authentication paths of the sliding-window Bloom filter MMR. If this MMR has a height of 20, which will be reached when the total number of outputs is ~8M, these 45 authentication paths take up 4.500 `BFieldElement`s. The block proof being ~125.000 `BFieldElement`s and the old block size limit 250.000, this only leaves room for 125.000 / 4.500 ~= 28 inputs! And that's assuming that the mutator set accumulator takes up no space, and that there are no outputs.
With this increase, the practical limit on the number of inputs per block rises to ~195, which is still quite low but should be enough for …
> fork!: Increase block size

- src/models/blockchain/block/block_info.rs
I did not experience any issues as I pointed neptune-explorer to a neptune-core node running this patch. It looks like the unexpected field is just being ignored. Regardless, I have a PR for neptune-explorer coming soon.
> feat: Expand `BlockInfo` with `size`

- src/peer_loop.rs
When rejecting a block proposal notification, an info message is logged showing the reason why it was rejected. This commit changes that info message to include the rejected proposal's guesser fee.
This change answers a request made by a composer who would like to know what fees other competing composers are offering, in order to adapt their own price.
> style: Report guesser fee of rejected blocks

- scripts/python/geo_command_runner.py
Example use (in a screen or tmux tab):
> python3 scripts/python/geo_command_runner.py neptune-cli header tip
Co-authored-by: Perplexity.ai
> devx: Add script for tracking average RPC response time

- .github/workflows/no_lock_build.yml
- Cargo.lock
- Cargo.toml
- introduce a workflow to check that `neptune-core` can be built in the absence of a `Cargo.lock`, as is the case when using it as a dependency
- fix the version of a transitive dependency that recently started introducing build failures
> Pin version of build-breaking transitive dependency

- src/models/blockchain/transaction/mod.rs
- src/models/state/mempool.rs
Anytime a SingleProof-backed transaction has its mutator set data updated, it must be such that the updated transaction *always* replaces the existing transaction. This commit adds a test to that effect, as this was not previously always the case.
> test(mempool): Ensure MS-updated transaction always replaces progenitor

- src/mine_loop.rs
- src/models/state/mempool.rs
- src/tests/shared.rs
When returning a list of transactions for inclusion in a block, only those transactions with a mutator set hash matching the expected value should be returned, as any other transactions cannot directly be merged into a block.
> feat(mempool): Filter transactions for mutator set match

- src/config_models/cli_args.rs
- src/config_models/fee_notification_policy.rs
- src/config_models/mod.rs
- src/main_loop/proof_upgrader.rs
- src/mine_loop.rs
- src/mine_loop/composer_parameters.rs
- src/models/blockchain/block/mod.rs
- src/models/blockchain/transaction/mod.rs
- src/models/state/archival_state.rs
- src/models/state/mempool.rs
- src/models/state/mod.rs
- src/models/state/wallet/mod.rs
- src/models/state/wallet/scan_mode_configuration.rs
- src/models/state/wallet/secret_key_material.rs
- src/models/state/wallet/transaction_output.rs
- src/models/state/wallet/utxo_notification.rs
- src/models/state/wallet/wallet_configuration.rs
- src/models/state/wallet/wallet_entropy.rs
- src/models/state/wallet/wallet_state.rs
- src/tests/shared.rs
This PR:
- Introduces a CLI flag that regulates the notification policy for prover fees (meaning upgrader fees and composition fees, guesser fees are explicitly excluded). The notification policy can be
- `OnChainSymmetric` (default)
- `OffChain` (for users who know what they are doing)
- `OnChainGeneration` (anticipates cold composing/upgrading, where the client mines to an address but does not know the spending key).
- Streamlines the CLI arguments, and how it is passed down to global state and wallet state.
- Implements and tests the fee notification policy.
- Automatically derives and tracks the symmetric (in addition to generation, which was already being done) key with derivation index 0. The default fee notification policy is to use this symmetric key.
- Adds a step in scan mode …
> Regulate prover fee notifications

- src/main_loop/proof_upgrader.rs
- src/models/state/mod.rs
- src/tests/shared.rs
After a proof-upgrade is completed, the associated transaction might no longer be valid because it was mined, or in the case of a merge-proof, one of the inputs to the transaction might have been mined. This commit verifies that the transction is still confirmable before sharing it with peers.
> fix(proof_upgrader): Check for double-spending

- src/config_models/data_directory.rs
- src/lib.rs
- src/models/state/wallet/migrate_db/v0_to_v1.rs
- src/models/state/wallet/rusty_wallet_database.rs
- src/models/state/wallet/wallet_configuration.rs
- src/models/state/wallet/wallet_state.rs
- src/tests/shared.rs
closes #577
It is important to backup wallet db before migrating in case:
1. anything goes wrong with the migration
2. user needs to downgrade the software for some reason.
This refactors RustyWalletDatabase::connect() into two methods try_connect() and try_connect_and_migrate().  The former returns an error that indicates if the DB needs to be migrated.
WalletState (which has DB path info) calls try_connect() and performs a backup if needed. It then calls try_connect_and_migrate().
`WalletState::backup_database()` simply copies the "wallet" directory to `<wallet_db_name>-schema-v<schema-version>.bak.<count>`. For example the first backup of v0 wallet db would be: wallet-schema-v0.bak.1.  This is in the same parent directory as the original `wallet` db directory.  An alternative could be …
> backup wallet DB before migrating

- src/models/blockchain/block/mod.rs
- src/models/blockchain/block/mutator_set_update.rs
- src/models/state/mod.rs
- src/models/state/wallet/wallet_state.rs
- src/tests/shared.rs
Cf. #568.
Function `resync_membership_proofs_from_stored_blocks` contains a logical error (now fixed) by failing to update the `RemovalRecords` in the course of updating a `MsMembershipProof` with a `MutatorSetUpdate`.
Test `resync_ms_membership_proofs_across_stale_fork` missed the opportunity to catch this logic error. It triggered the above function but only with sequences of blocks devoid of `RemovalRecord`s. Now the sequences of blocks have a nontrivial number of `RemovalRecord`s and `AdditionRecord`s. Without the above above fix in `resync_membership_proofs_from_stored_blocks`, this updated test reliably triggers some logic error related to mutator sets in that function.
Also: refactor mock block generators to facilitate the changes to the test.
> Fix MSMP Resync From Blocks

- src/api/tx_initiation/error.rs
- src/job_queue/errors.rs
- src/job_queue/job_completion.rs
- src/job_queue/job_handle.rs
- src/job_queue/job_result_wrapper.rs
- src/job_queue/mod.rs
- src/job_queue/queue.rs
- src/job_queue/traits.rs
- src/mine_loop.rs
- src/models/proof_abstractions/tasm/program.rs
- src/models/proof_abstractions/tasm/prover_job.rs
note: this PR does not change neptune-core logic.  Only JobQueue API.  I am intending to merge it immediately once CI is happy.  I am making it a PR for a) CI checks, b) to document, and c) in case anyone wishes to review/comment post-hoc.
-------------------
This is a follow-up to #579 that implements some ergonomic improvements to the JobQueue especially with regards to JobResult conversions.
A key features of the JobQueue is that a single JobQueue can accept Jobs of arbitrary (dyn) type and those jobs can return results of arbitrary (dyn) type.  This flexibility comes at a cost:  The type returned by each Job must impl the JobResult trait.  And the caller awaiting the job must downcast the result into the expected type, which is verbose/ugly and kind of uncommon.
The key innovation in …
> feat: improve job_queue ergonomics

- cliff.toml
- src/mine_loop.rs
- src/models/blockchain/block/mock_block_generator.rs
- src/models/blockchain/block/mod.rs
- src/models/state/wallet/transaction_output.rs
- src/models/state/wallet/wallet_state.rs
- src/tests/shared.rs
If a block is empty, i.e. contains no inputs and only the coinbase rewards, *and* the composer chooses to reward the entire block subsidy to the guesser, there is no need for the composer to add any outputs to the coinbase transaction.
Prior to this commit, the composer would in that scenario add two ouputs to the coinbase transaciton. Many such blocks with two zero-valued outputs exist on main net today, so this is not a hypothetical scenario.
Avoiding these zero-valued outputs has two benefits:
- It leaves more room for other transactions to be merged into the block.
- It avoids zero-valued leafs in the AOCL whose presence would otherwise reduce the anonymity set as zero valued leafs are less likely to be spent than any other leafs and can, in the case of an empty block, be identified …
> privacy(mine_loop): Never add zero-valued composer outputs

- Cargo.lock
- Cargo.toml
- src/util_types/mutator_set/chunk.rs
Add a test that computes statistics about the number of elements in `Chunk`s. Based on these statistics, it is justifiable to use 12 bits to store the length.
> test(`Chunk`): Add test computing statistics of `Chunk` lengths

- .gitignore
- src/lib.rs
- src/main_loop/proof_upgrader.rs
- src/mine_loop.rs
- src/models/blockchain/block/mod.rs
- src/models/blockchain/block/validity/block_program.rs
- src/models/proof_abstractions/tasm/program.rs
- src/models/state/archival_state.rs
- src/models/state/mempool.rs
- src/models/state/mod.rs
- src/models/state/wallet/mod.rs
- src/models/state/wallet/transaction_output.rs
- src/models/state/wallet/wallet_state.rs
- src/peer_loop.rs
- src/rpc_server.rs
- src/tests/shared.rs
- src/util_types/mutator_set/chunk.rs
test: Recover state from real main net blocks
Add a test of `GlobalState::bootstrap_from_directory` using real data
from main net. The test uses the `blk0.dat` file from a node that has
been online since genesis, thus containing reorganizations that some
previously untested branches of `GlobalState::bootstrap_from_directory`.
This test also serves as a check that the first 113 main net blocks are
still considered valid by future versions of the software.
Closes #515 
This PR introduces a big file, `blk0.dat`, added with `git lfs`. But an alternative would be to download the `blk0.dat` from our test servers instead, and store it in `test_data` so that it would only ever have to be downloaded once.
> Test real blocks

- benches/wallet_state.rs
- src/api/regtest/regtest_impl.rs
- src/api/tx_initiation/builder/transaction_details_builder.rs
- src/bench_helpers.rs
- src/main_loop.rs
- src/main_loop/proof_upgrader.rs
- src/mine_loop.rs
- src/models/blockchain/block/mock_block_generator.rs
- src/models/blockchain/block/mod.rs
- src/models/blockchain/block/validity/block_primitive_witness.rs
- src/models/blockchain/block/validity/block_program.rs
- src/models/blockchain/transaction/mod.rs
- src/models/state/archival_state.rs
- src/models/state/block_proposal.rs
- src/models/state/mempool.rs
- src/models/state/mod.rs
- src/models/state/wallet/mod.rs
- src/models/state/wallet/wallet_state.rs
- src/peer_loop.rs
- src/rpc_server.rs
- src/tests/shared.rs
The peer loop should act as a robust firewall against invalid blocks.
Nevertheless, it is worth ensuring that handlers behind that firewall
cannot crash even for invalid blocks.
In particular, function `Block::total_guesser_reward` and other
helper functions downstream from there, are undefined for
un-validated blocks. The result should be wrapped in a `Result`, in
order to avoid passing inconsistent values up the call graph. This
change cascades into many function return type modifications
and many `.unwrap`s and `.expect`s downstream.
The inconsistency was exposed by test
`rpc_server::rpc_server_tests::public_announcements_in_block_test`
which is now fixed instead of ignored. Thanks to @skaunov for PR #543
and the effort leading to this exposition.
Also:
- Change logic for computing …
> Gracefully catch errors resulting from invalid blocks

- src/models/blockchain/block/mod.rs
- src/models/blockchain/transaction/mod.rs
- src/models/blockchain/transaction/primitive_witness.rs
- src/models/blockchain/transaction/utxo_triple.rs
- src/models/state/mod.rs
- src/models/state/wallet/address/mod.rs
- src/models/state/wallet/expected_utxo.rs
- src/models/state/wallet/incoming_utxo.rs
- src/models/state/wallet/transaction_output.rs
- src/models/state/wallet/wallet_state.rs
This PR is a follow-up to #630 (assuming that that will be merged mostly without changes) but conceptually separate.
Introduce a new type `UtxoTriple` containing the preimage to the addition record -- which is to say, the UTXO, the sender randomness, and the receiver digest. This triple appears all over the place. Now it has a name. As a side effect, many calls to `mutator_set::commit` can now be funneled through the new struct: 1) create a `UtxoTriple` object, and 2) invoke convenience function `addition_record()`.
This type does not already exist. Near misses:
- `TxOutput` -- contains other fields.
- `IncomingUtxo` -- contains the receiver *preimage* not receiver *digest*.
- `ExpectedUtxo` -- both.
> Introduce new type `UtxoTriple`

- neptune-core/src/models/blockchain/block/mod.rs
- neptune-core/src/models/state/mod.rs
- neptune-core/src/models/state/wallet/mod.rs
- neptune-core/src/models/state/wallet/wallet_entropy.rs
- neptune-core/tests/common/genesis_node.rs
- neptune-core/tests/consensus_rules_unchanged.rs
Since the block structure is different in production from what it is under the test flag, this tests, that checks the validity of the first ~120 mainnet blocks, cannot live under the test flag. So it's added as an integration test.
Unfortunately some test helper function were needed for this test to work, and since they can't be under the test flag, they are added as local functions in the new test. The alternative seems to be to pull the test helper functions in question out from under the test flag but that would require new dependencies in production code (namely HTTP client 'clienter') which I think is not preferable. So local functions was the best compromise I could come up with. Happy to have other people give me better ideas.
> test: re-enable test that first blk-file contains valid blocks

- .github/workflows/release.yml
```
-        if: "runner.os != 'Windows'"
+        if: ${{runner.os != 'Windows'}}
```
The former denotes a string literal. The latter denotes an expression that is evaluated at run-time. Not sure why GitHub CI did not object harder earlier.
> ci(`release.yml`): Fix syntax

- neptune-core/src/config_models/cli_args.rs
- neptune-core/src/config_models/mod.rs
- neptune-core/src/config_models/tx_upgrade_filter.rs
- neptune-core/src/main_loop/proof_upgrader.rs
- neptune-core/src/mine_loop.rs
- neptune-core/src/models/blockchain/transaction/validity/proof_collection.rs
- neptune-core/src/models/state/mempool.rs
- neptune-core/src/models/state/mod.rs
- neptune-core/src/models/state/transaction_kernel_id.rs
To avoid double work if the same entity is controlling multiple nodes that are performing proof upgrades, a filter is introduced. The filter looks at the `TransactionKernelId` value and performs a modulus operation and compares the remainder with that set in the filter. If the transaction is not a match, no proof upgrading is done (unless the node has a financial interest in the transaction).
If an entity is controlling three proof upgrading nodes, values for this filter could be set to "3:0" on the 1st machine, "3:1" on the 2nd, and "3:2" on the 3rd machine. This way, the entity avoids that the machines do duplicate work, *and* they cover all transactions on the network.
> feat: Add tx filter for proof upgrading

- .cargo/config.toml
Implementing suggested fix in CI's build error message: Setting an environment variable to force a newer version of cmake to be used.
Error in CI:
```
error: failed to run custom build command for `leveldb-sys v2.0.9`
Caused by:
process didn't exit successfully: `/home/runner/work/neptune-core/neptune-core/target/debug/build/leveldb-sys-adc7eb3218f47677/build-script-build` (exit status: 101)
--- stdout
[build] Started
[snappy] Building
CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
HOST_CMAKE_TOOLCHAIN_FILE = None
CMAKE_TOOLCHAIN_FILE = None
CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
HOST_CMAKE_GENERATOR = None
CMAKE_GENERATOR = None
CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = …
```
> ci: Fix cmake version problem

- neptune-core/src/state/archival_state.rs
fixes #471
The issue was that block records were being written to DB before written to blkXX.dat files on disk, which resulted in mis-match when power is lost during a call to ArchivalState::store_block().  Upon startup, a SIGBUS occurs when reading the mmap'd data.
Fixes:
1. root cause: calls mmap.flush() after writing block to ensure it is written to disk before writing matching record to DB.
2. avoid SIGBUS: verifies we do not attempt to read past end of file. Returns error with diagnostic info if so, which gets logged.
> fix: ensure block data written before db

- Cargo.toml
Also make use of incremental compilation in dev and test profiles.
Since we usually do not have to create Triton VM proofs when the tests are running, we might as well compile with less optimization. I personally only ever use the dev profile in my IDE, so that should compile as fast as possible, without regard to the performance of the compiler output.
> devops: Faster compilation by lowering some `opt-level`s

- neptune-core/src/application/loops/peer_loop.rs
Reduce the number of blocks returned and requested in a batch request, from 250 blocks to 35 blocks.
In retrospect, 250 blocks is way too much as each block is at least 1MB, meaning that the message size is above 250MB. Such big messages cannot be sent or received within the `INDIVIDUAL_PEER_SYNCHRONIZATION_TIMEOUT` interval, 120 seconds, on weak connections, as the required transfer speed is above 2MB/s, not including the time it takes for the peer to read all the blocks from disk. This new standard size of 35 blocks only requires a transfer speed of 290kB/s, which is probably more reasonable.
This is just an iterative improvement for initial block download. Other important steps are the upcoming parallel downloading of blocks from multiple peers and potentially the switch to libp2p. …
> refactor(peer_loop): Reduce block batch size
