src/bin/neptune-cli.rs
src/main_loop.rs
src/models/state/mod.rs
src/models/state/wallet/mod.rs
src/models/state/wallet/monitored_utxo.rs
src/models/state/wallet/wallet_state.rs
src/rpc_server.rs

Mark monitored UTXOs as abandoned if UTXO got confirmed in abandoned fork.

Mark mutxos as abandoned

---

src/mine_loop.rs
src/models/blockchain/transaction/mod.rs
src/models/blockchain/transaction/transaction_kernel.rs
src/models/blockchain/transaction/utxo.rs
src/models/blockchain/transaction/validity.rs
src/models/blockchain/transaction/validity/kernel_to_lock_scripts.rs
src/models/blockchain/transaction/validity/kernel_to_typescripts.rs
src/models/blockchain/transaction/validity/lockscripts_halt.rs
src/models/blockchain/transaction/validity/removal_records_integrity.rs
src/models/blockchain/transaction/validity/tasm/removal_records_integrity.rs
src/models/blockchain/transaction/validity/typescripts_halt.rs
src/models/state/mod.rs
src/tests/shared.rs

Clean up transaction validation logic somewhat.

New secretwitness trait

---

src/models/blockchain/block/difficulty_control.rs
src/models/blockchain/block/mod.rs
src/models/blockchain/transaction/validity/update.rs
src/models/proof_abstractions/timestamp.rs

+= for TimeStamp

---

.github/workflows/main.yml
src/mine_loop.rs
src/models/blockchain/block/block_body.rs
src/models/blockchain/block/block_height.rs
src/models/database.rs
src/models/state/archival_state.rs
src/models/state/mod.rs
src/models/state/wallet/monitored_utxo.rs
src/models/state/wallet/wallet_state.rs

Should be merged after #273, as this PR includes its commits.

Hash rate independent of tx size

---

src/models/state/wallet/address/generation_address.rs

We serde(skip) fields that can be computed from the seed and then manually impl Deserialize to populate those fields.  This makes the serialized representation smaller including bech32m.  SpendingKey are not transmitted/stored much, so this is only a minor improvement.
I was hoping to do the same thing for GenerationReceivingAddress in order to reduce its (huge) bech32m representation, however that does not appear to be possible because all of its fields are derived from the original (secret) seed and none are derived from the public key.    It seems we could possibly make recipient_id derive from the pubkey, and then the spending-key could also derive it from pubkey so they match.  So that would be a minor reduction in size.  Perhaps with some study we could figure out a more compact …

perf: serialize only 'seed' field of GenerationSpendingKey

---

src/connect_to_peers.rs

This PR makes all log messages stemming from the peer loop include the peer address they pertain to. This answers a personal frustration but before merging into master I thought I would offer the opportunity for push-back in case it is more controversial than I thought.

log: Add peer address to peer-loop log messages

---

src/lib.rs
src/main.rs
src/main_loop.rs
src/main_loop/proof_upgrader.rs
src/mine_loop.rs
src/models/channel.rs
src/models/proof_abstractions/tasm/prover_job.rs
src/models/state/mempool.rs

A possible way of ensuring graceful shutdown on composition failure. Still prints stack traces.

feat(mine_loop): Graceful shutdown on composition failure

---

src/connect_to_peers.rs

There is a back-stop in place to ensure that the maximum number of peers can never be exceeded, even accounting for race conditions. However, the behavior of bootstrapper nodes is to disconnect from the longest-lived node whenever the maximum is reached. In this case, control might reach the backstop before the instruction to disconnect has been processed.
The solution is to disable the backstop whenever a corresponding disconnect-from-longest-lived-peer message has been spawned -- that is, ignore the backstop when the node is configured to bootstrap with the CLI argument `--bootstrap`.
@elielnfinic's analysis was invaluable for tracking down the root cause of this bug.
Fixes #287.
@Co-authored-by: @elielnfinic <46634774+elielnfinic@users.noreply.github.com>

fix: Temporarily exceed max num peers when bootstrapping

---

src/bin/dashboard_src/send_screen.rs
src/bin/neptune-cli.rs
src/models/peer.rs
src/peer_loop.rs
src/rpc_server.rs

370 dashboard send fee

---

src/rpc_server.rs

Improving RPC inline documentation - addresses #339

Improving RPC inline documentation

---

src/models/blockchain/block/block_header.rs

feat : Adding block difficulty and version to block header display #390

---

src/main_loop.rs

Before sharing own block proposal, verify that it is valid.
Acts as a sanity check that the composition is valid. If it isn't, that would indicate an error in the application.

refactor: Check validity of own block proposal

---

src/bin/neptune-cli.rs
src/models/state/wallet/wallet_status.rs

The CLI command `wallet-status` produces unwieldy output even for a modest number of wallet status elements. This commit adds another option for exporting: formatted as a markdown table. Specifically, the CLI command now takes an optional flag `--table`, in which case the table is outputted instead of the JSON data dump. Optional flag `--json` produces the original JSON data dump. Not including either flag defaults to the original JSON data dump, so in particular no old behaviors of the CLI tool have changed.
I thought I would let this commit live as a PR for a while before merging. I don't think it's particularly controversial but you never know what kind of review feedback you get.

feat(CLI): Show wallet status as table

---

.github/workflows/main.yml
src/locks/std/atomic_mutex.rs
src/locks/std/atomic_rw.rs
src/locks/tokio/atomic_mutex.rs
src/locks/tokio/atomic_rw.rs
src/models/blockchain/block/block_validation_error.rs
src/models/blockchain/block/mod.rs
src/models/blockchain/transaction/validity/tasm/coinbase_amount.rs
src/models/blockchain/type_scripts/native_currency_amount.rs
src/models/proof_abstractions/tasm/prover_job.rs
src/models/proof_abstractions/verifier.rs
src/models/state/transaction_details.rs
src/models/state/wallet/address/address_type.rs
src/models/state/wallet/expected_utxo.rs
src/models/state/wallet/incoming_utxo.rs
src/models/state/wallet/monitored_utxo.rs
src/models/state/wallet/utxo_notification.rs
src/models/state/wallet/wallet_state.rs
src/peer_loop.rs
src/util_types/mutator_set/removal_record.rs

Alert to regressions by `cargo doc`umenting private items in CI.

Update intra-doc links of private items

---

src/bin/neptune-cli.rs
src/connect_to_peers.rs
src/models/blockchain/block/difficulty_control.rs
src/models/blockchain/type_scripts/native_currency_amount.rs
src/models/peer/transfer_block.rs
src/models/state/mod.rs
src/models/state/wallet/address/common.rs
src/models/state/wallet/address/encrypted_utxo_notification.rs
src/models/state/wallet/address/generation_address.rs
src/models/state/wallet/address/symmetric_key.rs
src/models/state/wallet/utxo_notification.rs
src/models/state/wallet/wallet_file.rs
src/models/state/wallet/wallet_state.rs

- Decrease general nesting depth.
- Adhere to maximum line length (in the changed parts).
- Replace some (nested) match statements with `map` and `map_err` as appropriate.

style: Use `ensure!` over `if … { bail! }`

---

src/main_loop.rs

Note that [`Interval::tick`](https://docs.rs/tokio/latest/tokio/time/struct.Interval.html#method.tick) has [different semantics](https://docs.rs/tokio/latest/tokio/time/index.html#examples) than the previous, manual implementation using [`sleep`](https://docs.rs/tokio/latest/tokio/time/fn.sleep.html). I think the new semantics are the intended ones.

Use `tokio::interval` over `sleep`

---

src/peer_loop.rs

Two tokio tasks can run simultaneously that establish a connection incoming/outgoing to the same peer. If a write lock is not held over some final checks before a connection is established then two connections to the same peer might be made.
This reintroduces the holding of a lock while this final check is being made. The lock was removed in commit fa89d0414.

fix(peer_loop): fix race condition on new connection

---

benches/fast_kernel_mast_hash.rs
src/config_models/cli_args.rs
src/config_models/network.rs
src/mine_loop.rs
src/models/blockchain/block/block_header.rs
src/models/blockchain/block/block_kernel.rs
src/models/blockchain/block/difficulty_control.rs
src/models/blockchain/block/mock_block_generator.rs
src/models/blockchain/block/mod.rs
src/models/blockchain/block/pow.rs
src/models/channel.rs
src/models/peer.rs
src/models/state/archival_state.rs
src/models/state/mod.rs
src/models/state/wallet/wallet_state.rs
src/peer_loop.rs
src/rpc_server.rs
src/tests/shared/blocks.rs
src/util_types/mutator_set/msa_and_records.rs

This merged branch changes the proof-of-work puzzle from partial preimage search to  a puzzle involving Merkle trees. The main benefit is that as the new puzzle requires a lot of memory (and memory reads) for efficient guessing, the computational disparity between general purpose computing hardware and specialized computing hardware is significantly reduced.

feat: Memory-hard proof-of-work

---

neptune-core/src/models/proof_abstractions/tasm/program.rs

Ensure deterministic proofs in tests by setting the RNG seed used by the Triton VM prover. This breaks zero-knowledge of the proofs used for tests. This is motivated by the block hash depending on the block proof meaning that if two different machines start a test simultaneously, they would otherwise not generate the same proofs and, worse, will disagree on block hashes and mutator sets if these proofs are used for blocks.
This closes #657.

test: Ensure deterministic STARK proofs

---

neptune-core/src/application/rpc/server.rs
neptune-core/src/state/wallet/wallet_state.rs

The RPC call `list-utxos` returns `UiUtxo`s from three sources:
1. the wallet database of monitored UTXOs;
2. the wallet database of expected UTXOs;
3. the mempool.
It is possible for the same `UiUtxo` to be present in more than one of these sources. Previously that would generate duplicate entries in the list of `UiUtxo`s returned by `list-utxos`. This commit changes that behavior by filtering out duplicates.
Furthermore, it changes the order of (2) and (3), so that if the `UiUtxo` comes from the mempool, it is not marked as "expected" when happens to also be present in the expected UTXOs database.
Lastly, the signature of mempool function `mempool_unspent_utxos_iter` is changed to accommodate this duplicate filter.
Fixes #710.

fix(RPC): Filter out duplicate `UiUtxo`s
